-- 코드를 작성해주세요

SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO AS I JOIN ITEM_TREE AS T ON I.ITEM_ID = T.ITEM_ID
WHERE NOT EXISTS(
    SELECT * FROM ITEM_TREE 
    WHERE I.ITEM_ID = PARENT_ITEM_ID
)
ORDER BY ITEM_ID DESC