-- 코드를 입력하세요 테이블에서 2022년 4월 13일 취소되지 않은 흉부외과(CS) 진료 예약 내역을 조회하는 SQL문을 작성해주세요
SELECT A.APNT_NO, P.PT_NAME, A.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM PATIENT AS P JOIN APPOINTMENT AS A ON P.PT_NO = A.PT_NO 
    JOIN DOCTOR AS D ON D.DR_ID = A.MDDR_ID 
WHERE A.APNT_CNCL_YN ='N' AND A.MCDP_CD = 'CS' AND DATE_FORMAT(A.APNT_YMD, "%Y-%m-%d") = "2022-04-13"
ORDER BY A.APNT_YMD ASC